package com.example.localization

import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.unit.LayoutDirection

enum class AppLanguage(val code: String, val displayName: String, val flag: String, val layoutDirection: LayoutDirection) {
    ARABIC("ar", "العربية", "🇩🇿", LayoutDirection.Rtl),
    FRENCH("fr", "Français", "🇫🇷", LayoutDirection.Ltr),
    ENGLISH("en", "English", "🇬🇧", LayoutDirection.Ltr)
}

data class StringsDefinition(
    val appTitle: String,
    val appSubtitle: String,
    val agentBadge: String,
    val sentinelConnected: String,
    val telemetryTitle: String,
    val telemetrySubtitle: String,
    val soilMoisture: String,
    val soilMoistureSub: String,
    val evapotranspiration: String,
    val evapotranspirationSub: String,
    val soilTemp: String,
    val soilTempSub: String,
    val waterSavings: String,
    val waterSavingsSub: String,
    val servicesTitle: String,
    val strategicCropsTitle: String,
    val strategicCropsSubtitle: String,
    val quickScan: String,
    // Nav tabs
    val navDashboard: String,
    val navDiagnosis: String,
    val navWaterAdvisor: String,
    val navQuantum: String,
    val navSafety: String,
    // Service cards
    val cardDiagnosisTitle: String,
    val cardDiagnosisDesc: String,
    val cardWaterTitle: String,
    val cardWaterDesc: String,
    val cardQuantumTitle: String,
    val cardQuantumDesc: String,
    val cardSafetyTitle: String,
    val cardSafetyDesc: String,
    // Floating agent button
    val agentButtonTitle: String,
    val agentButtonSubtitle: String,
    // Diagnosis screen
    val diagHeaderTitle: String,
    val diagHeaderSubtitle: String,
    val diagInputPrompt: String,
    val diagPlaceholder: String,
    val diagTakePhoto: String,
    val diagGallery: String,
    val diagStartBtn: String,
    val diagAnalyzing: String,
    val diagReportTitle: String,
    // Water Advisor
    val waterHeaderTitle: String,
    val waterHeaderSubtitle: String,
    val waterEvapoBanner: String,
    val waterEvapoTip: String,
    val waterChooseCrop: String,
    val waterMoistureLevel: String,
    val waterDailyReq: String,
    val waterBestTiming: String,
    val waterDoctorTip: String,
    // Quantum Optimization
    val quantumHeaderTitle: String,
    val quantumHeaderSubtitle: String,
    val quantumEfficiencyTitle: String,
    val quantumEfficiencyDesc: String,
    // Safety
    val safetyHeaderTitle: String,
    val safetyHeaderSubtitle: String,
    val safetyWarningNotice: String,
    val safetyGoldenRulesTitle: String,
    val safetyPhiTableTitle: String,
    val safetyContactsTitle: String
)

val ArabicStrings = StringsDefinition(
    appTitle = "زرعي AI",
    appSubtitle = "المرصد السيبراني للوقاية الزراعية وترشيد السقي",
    agentBadge = "Doctor 3.0",
    sentinelConnected = "SENTINEL متصل",
    telemetryTitle = "مستشعرات الحقول الحية (Field Telemetry)",
    telemetrySubtitle = "تحديث لحظي • الأقمار الصناعية",
    soilMoisture = "رطوبة التربة",
    soilMoistureSub = "سعة حقلية مثلى",
    evapotranspiration = "البخر-نتح ET₀",
    evapotranspirationSub = "يومياً (مستوى متوسط)",
    soilTemp = "حرارة التربة",
    soilTempSub = "عمق 25 سم",
    waterSavings = "توفير السقي",
    waterSavingsSub = "كفاءة هيدرولوجية",
    servicesTitle = "بوابات الخدمات الزراعية المتخصصة:",
    strategicCropsTitle = "المحاصيل الاستراتيجية الوطنية:",
    strategicCropsSubtitle = "الجزائر والمغرب العربي",
    quickScan = "فحص فوري",
    navDashboard = "الرئيسية",
    navDiagnosis = "التشخيص",
    navWaterAdvisor = "مستشار الري",
    navQuantum = "تحسين المياه",
    navSafety = "إرشادات الأمان",
    cardDiagnosisTitle = "التشخيص الذكي",
    cardDiagnosisDesc = "فحص ميكروسكوبي وكشف الآفات بالصور",
    cardWaterTitle = "مستشار الري",
    cardWaterDesc = "حساب المقننات المائية والرطوبة الحقلية",
    cardQuantumTitle = "تحسين المياه",
    cardQuantumDesc = "استراتيجيات هيدروديناميكية لمكافحة الشح",
    cardSafetyTitle = "إرشادات الأمان",
    cardSafetyDesc = "دليل فترات الأمان PHI والجرعات المعتمدة",
    agentButtonTitle = "الوكيل الذكي",
    agentButtonSubtitle = "استشارة فورية مع طبيب النباتات",
    diagHeaderTitle = "التشخيص الذكي للأمراض والآفات",
    diagHeaderSubtitle = "فحص بصري ميكروسكوبي بالذكاء الاصطناعي لكافة المحاصيل",
    diagInputPrompt = "رفع عينة نباتية أو وصف الأعراض السريرية:",
    diagPlaceholder = "صف شكل البقع، التفاف الأوراق، أو نوع المحصول...",
    diagTakePhoto = "التقاط بالكاميرا",
    diagGallery = "معرض الصور",
    diagStartBtn = "بدء الفحص بالذكاء الاصطناعي",
    diagAnalyzing = "جاري الفحص الميكروسكوبي الرقمي ومسح الأنسجة...",
    diagReportTitle = "تقرير الفحص المخبري النهائي:",
    waterHeaderTitle = "مستشار الري الذكي",
    waterHeaderSubtitle = "حساب المقننات المائية والرطوبة الحقلية لجميع المحاصيل",
    waterEvapoBanner = "مؤشرات البخر-نتح المرجعي (ET₀ اليوم)",
    waterEvapoTip = "معدل التبخر مرتفع نسبياً. يوصى بتعديل جرعات السقي وفق نظام التنقيط الليلي أو الفجري لتوفير 30% من استهلاك المضخة.",
    waterChooseCrop = "اختر المحصول لحساب برنامج الري:",
    waterMoistureLevel = "مستوى رطوبة التربة المقدر:",
    waterDailyReq = "المقنن المائي اليومي:",
    waterBestTiming = "نافذة السقي الموصى بها:",
    waterDoctorTip = "نصيحة المهندس لمقاومة الشح المائي:",
    quantumHeaderTitle = "تحسين توزيع المياه الذكي",
    quantumHeaderSubtitle = "خوارزميات هيدروديناميكية متقدمة لمواجهة الشح المائي",
    quantumEfficiencyTitle = "مؤشر التوفير المائي الإجمالي",
    quantumEfficiencyDesc = "تعتمد النمذجة الرياضية المتقدمة المستوحاة من فيزياء السوائل على محاكاة جبهات البلل داخل التربة الزراعية، بما يضمن إيصال قطرات الماء مباشرة إلى الجذور دون أي تسرب عميق أو تبخر سطحي.",
    safetyHeaderTitle = "دليل الأمان والوقاية الزراعية",
    safetyHeaderSubtitle = "الاستخدام المسؤول للمبيدات وفترات الأمان (PHI)",
    safetyWarningNotice = "تحذير صارم: تجنب الرش العشوائي للمبيدات الفطرية والحشرية أو خلطها بجرعات غير مدروسة. الالتزام الصارم بفترات الأمان قبل الجني (PHI) يحمي صحة المستهلك والبيئة ويمنع مناعة الآفات. يُرجى مراجعة مهندس وقاية النباتات المعتمد في منطقتك.",
    safetyGoldenRulesTitle = "القواعد الذهبية الخمس للرش الزراعي الآمن:",
    safetyPhiTableTitle = "دليل فترات الأمان قبل الجني (Délai Avant Récolte - PHI)",
    safetyContactsTitle = "جهات الاتصال الرسمية للمساعدة والإرشاد الفلاحي:"
)

val FrenchStrings = StringsDefinition(
    appTitle = "Zira3i AI",
    appSubtitle = "Observatoire Cybernétique de Protection & Irrigation",
    agentBadge = "Doctor 3.0",
    sentinelConnected = "SENTINEL Connecté",
    telemetryTitle = "Télémétrie en Direct des Parcelles",
    telemetrySubtitle = "Flux Satellitaire en Temps Réel",
    soilMoisture = "Humidité du Sol",
    soilMoistureSub = "Capacité au champ optimale",
    evapotranspiration = "Évapotranspiration ET₀",
    evapotranspirationSub = "Niveau journalier modéré",
    soilTemp = "Température Sol",
    soilTempSub = "Profondeur 25 cm",
    waterSavings = "Économie d'Eau",
    waterSavingsSub = "Efficacité hydrologique",
    servicesTitle = "Services Agricoles Spécialisés :",
    strategicCropsTitle = "Cultures Stratégiques Nationales :",
    strategicCropsSubtitle = "Algérie & Maghreb",
    quickScan = "Scan Direct",
    navDashboard = "Accueil",
    navDiagnosis = "Diagnostic",
    navWaterAdvisor = "Conseiller Eau",
    navQuantum = "Optimisation",
    navSafety = "Sécurité & PHI",
    cardDiagnosisTitle = "Diagnostic IA",
    cardDiagnosisDesc = "Analyse microscopique et détection de maladies par photo",
    cardWaterTitle = "Conseiller Eau",
    cardWaterDesc = "Calcul des doses d'irrigation et suivi de l'humidité",
    cardQuantumTitle = "Hydro-Optimisation",
    cardQuantumDesc = "Stratégies hydrodynamiques face au stress hydrique",
    cardSafetyTitle = "Guide Sécurité",
    cardSafetyDesc = "Délais avant récolte (DAR/PHI) et dosages agréés",
    agentButtonTitle = "Agent IA",
    agentButtonSubtitle = "Consultation instantanée avec l'agronome virtuel",
    diagHeaderTitle = "Diagnostic Intelligent des Maladies",
    diagHeaderSubtitle = "Inspection visuelle et pathologique par IA pour toutes cultures",
    diagInputPrompt = "Téléchargez un échantillon végétal ou décrivez les symptômes :",
    diagPlaceholder = "Décrivez les taches, enroulement des feuilles ou variété...",
    diagTakePhoto = "Prendre Photo",
    diagGallery = "Galerie",
    diagStartBtn = "Lancer l'Analyse IA",
    diagAnalyzing = "Analyse microscopique et examen des tissus en cours...",
    diagReportTitle = "Rapport Pathologique Final :",
    waterHeaderTitle = "Conseiller en Irrigation Précise",
    waterHeaderSubtitle = "Calcul des besoins hydriques et humidité pour toutes cultures",
    waterEvapoBanner = "Indice d'Évapotranspiration (ET₀ du Jour)",
    waterEvapoTip = "Taux d'évaporation élevé. Il est recommandé de privilégier le goutte-à-goutte matinal ou nocturne pour économiser 30% d'eau.",
    waterChooseCrop = "Sélectionnez une culture pour le plan d'irrigation :",
    waterMoistureLevel = "Niveau d'humidité estimé :",
    waterDailyReq = "Dose journalière requise :",
    waterBestTiming = "Fenêtre d'arrosage recommandée :",
    waterDoctorTip = "Conseil de l'ingénieur face à la sécheresse :",
    quantumHeaderTitle = "Optimisation Hydrique de Précision",
    quantumHeaderSubtitle = "Algorithmes hydrodynamiques face à la rareté de l'eau",
    quantumEfficiencyTitle = "Indice Global d'Économie d'Eau",
    quantumEfficiencyDesc = "Modélisation avancée simulant les fronts d'humectation pour délivrer l'eau directement aux racines actives sans percolation profonde ni évaporation de surface.",
    safetyHeaderTitle = "Guide Sécurité & Traitements",
    safetyHeaderSubtitle = "Utilisation raisonnée des produits phytosanitaires (DAR/PHI)",
    safetyWarningNotice = "Avertissement strict : Évitez les surdosages et mélanges anarchiques. Le respect strict des Délais Avant Récolte (DAR) préserve la santé publique et prévient les résistances parasitaires.",
    safetyGoldenRulesTitle = "Les 5 règles d'or pour un traitement sécurisé :",
    safetyPhiTableTitle = "Tableau des Délais Avant Récolte (DAR / PHI)",
    safetyContactsTitle = "Organismes officiels d'appui agricole :"
)

val EnglishStrings = StringsDefinition(
    appTitle = "Zira3i AI",
    appSubtitle = "Cybernetic Crop Protection & Smart Irrigation Observatory",
    agentBadge = "Doctor 3.0",
    sentinelConnected = "SENTINEL Connected",
    telemetryTitle = "Live Field Telemetry",
    telemetrySubtitle = "Real-Time Satellite Stream",
    soilMoisture = "Soil Moisture",
    soilMoistureSub = "Optimal field capacity",
    evapotranspiration = "Evapotranspiration ET₀",
    evapotranspirationSub = "Moderate daily rate",
    soilTemp = "Soil Temp",
    soilTempSub = "Depth 25 cm",
    waterSavings = "Water Savings",
    waterSavingsSub = "Hydrological efficiency",
    servicesTitle = "Specialized Agricultural Services:",
    strategicCropsTitle = "National Strategic Crops:",
    strategicCropsSubtitle = "Algeria & North Africa",
    quickScan = "Instant Scan",
    navDashboard = "Dashboard",
    navDiagnosis = "Diagnosis",
    navWaterAdvisor = "Water Advisor",
    navQuantum = "Quantum Water",
    navSafety = "Safety & PHI",
    cardDiagnosisTitle = "AI Diagnosis",
    cardDiagnosisDesc = "Microscopic visual analysis and pest identification",
    cardWaterTitle = "Water Advisor",
    cardWaterDesc = "Crop water requirements and field soil moisture tracking",
    cardQuantumTitle = "Quantum Water",
    cardQuantumDesc = "Hydrodynamic strategies for drought and water scarcity",
    cardSafetyTitle = "Safety & PHI",
    cardSafetyDesc = "Pre-Harvest Interval (PHI) and authorized pesticide protocols",
    agentButtonTitle = "AI Agent",
    agentButtonSubtitle = "Instant consultation with plant doctor",
    diagHeaderTitle = "Smart Pest & Disease Diagnosis",
    diagHeaderSubtitle = "AI-powered digital pathology for strategic crops",
    diagInputPrompt = "Upload a crop leaf photo or describe visible symptoms:",
    diagPlaceholder = "Describe spots, leaf curling, color change, or crop type...",
    diagTakePhoto = "Camera",
    diagGallery = "Gallery",
    diagStartBtn = "Run AI Diagnosis",
    diagAnalyzing = "Scanning plant tissue and calculating confidence score...",
    diagReportTitle = "Final Pathology Laboratory Report:",
    waterHeaderTitle = "Smart Irrigation Advisor",
    waterHeaderSubtitle = "Crop water requirements and root-zone moisture tracking",
    waterEvapoBanner = "Reference Evapotranspiration (Today's ET₀)",
    waterEvapoTip = "High daytime evaporation rate. Early morning or dawn drip irrigation saves 30% pump energy and prevents heat shock.",
    waterChooseCrop = "Select crop for irrigation schedule:",
    waterMoistureLevel = "Estimated soil moisture capacity:",
    waterDailyReq = "Daily water demand:",
    waterBestTiming = "Recommended irrigation window:",
    waterDoctorTip = "Agronomist's drought mitigation tip:",
    quantumHeaderTitle = "Quantum-Inspired Water Optimization",
    quantumHeaderSubtitle = "Hydrodynamic algorithms for water scarcity management",
    quantumEfficiencyTitle = "Overall Water Conservation Index",
    quantumEfficiencyDesc = "Advanced mathematical fluid modeling delivering moisture directly to active root capillaries with zero deep drainage or surface evaporation.",
    safetyHeaderTitle = "Safety & Agricultural Stewardship",
    safetyHeaderSubtitle = "Responsible pesticide dosage & Pre-Harvest Intervals (PHI)",
    safetyWarningNotice = "Strict Warning: Avoid random spraying or unauthorized pesticide mixing. Adhering to Pre-Harvest Intervals (PHI) protects consumer safety, the environment, and prevents pest resistance.",
    safetyGoldenRulesTitle = "Five Golden Rules for Safe Spraying:",
    safetyPhiTableTitle = "Pre-Harvest Interval (PHI) Guide",
    safetyContactsTitle = "Official Agricultural Support Contacts:"
)

val LocalAppStrings = staticCompositionLocalOf { ArabicStrings }
val LocalAppLanguage = staticCompositionLocalOf { AppLanguage.ARABIC }
